Trying to get the LiH example working with saving/loading good VQE results. For some reason the intermediate_statevector code breaks with the circuits output by the VQEUCCFactory code, giving the following error upon trying to rebuild the circuit:
qiskit.circuit.exceptions.CircuitError: "Bit 'Qubit(QuantumRegister(4, 'q'), 0)' is not in the circuit."